### PR TITLE
update get-portalrole

### PR DESCRIPTION
**Pull request by pglodowski**
updated the function to include multiple requests if there are more than 50 custom roles

### CODE REVIEW

**Comment by johnsarie27** [comment]
@pglodowski - It looks like either a) we don't have the query written properly to pull 50 roles or b) there's a bug in the REST API.  Try looking up the documentation to make sure our declaration of 50 roles is accurate.

**Comment by pglodowski** [comment]
@johnsarie27 - I should've been more specific, that was by design. I didn't want to create 50 custom roles so I just adjusted the request increment to 1 in the test function so that I could test with the 3 roles that the reference environment currently has.

**Comment by pglodowski** [comment]
@johnsarie27 Here's a test with only 3 custom roles, retrieving the max of 50:

image

**Comment by johnsarie27** [comment]
@pglodowski - Oh, haha... Thanks for clarifying that.  Any other issues before we merge the PR?

**Comment by pglodowski** [comment]
@johnsarie27 - no problem! I think we're good to go.

**Review by johnsarie27 — APPROVED** [review]
Looks good and tested by Phillip.

**Pull request merged**
